name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Authenticate to the server via ssh
# and run our deployment script
jobs:
  deploy-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /home/u298973981/public_html/ && ./.scripts/deploy.sh"
